Added a new boolean function - equals and int hashCode
mate-academy/jv-equals-hashcode pull request #11
Opened 2019-08-21 14:49 UTC by 4MoPDai

There was used Class Object and construction instanceof for different exceptions. And was created hashCode

2019-08-21 19:39 UTC, boroda4436 commented on src/main/java/core/basesyntax/Rectangle.java
> +        return 31 * length - 13 + 2 * this.width;
@4MoPDai why you are using 31, 13 and 2 in your solution?
this is just intersting for me. Why not for example 42 24 and 5?

2019-08-21 20:07 UTC, boroda4436 requested changes

2019-08-21 20:07 UTC, boroda4436 commented on src/main/java/core/basesyntax/Rectangle.java
> +        if (obj instanceof Rectangle) {
@4MoPDai please use color as well as length and width

2019-08-22 07:36 UTC, 4MoPDai commented on src/main/java/core/basesyntax/Rectangle.java
> +        return 31 * length - 13 + 2 * this.width;
> @4MoPDai why you are using 31, 13 and 2 in your solution?
> this is just intersting for me. Why not for example 42 24 and 5?
        // Я использую 31, 13, 2. Потому что это уменьшает колизи.
        // то есть уменьшает возможность похожего хэш-кода у других
        //объектов

2019-08-22 09:05 UTC, boroda4436 requested changes

2019-08-22 09:05 UTC, boroda4436 commented on src/main/java/core/basesyntax/Rectangle.java
> +            if (!this.length.equals(rectObj.length)) {
@4MoPDai please simplify your if statements

2019-12-03 07:55 UTC, closed without merging