add hw-32-equals
mate-academy/jv-equals-hashcode pull request #5
Opened 2019-08-21 10:47 UTC by TarasHryts

2019-08-21 15:10 UTC, Sofasmile commented on src/main/java/core/basesyntax/Rectangle.java
> +            return this.width.equals(width) && this.length.equals(length);
what about coler?

2019-08-21 15:12 UTC, TarasHryts commented on src/main/java/core/basesyntax/Rectangle.java
> +            return this.width.equals(width) && this.length.equals(length);
чтобы equals()
 * сравнивал экземпляры Rectangle по содержимому полей width и length
i do not need it

2019-08-21 20:03 UTC, boroda4436 commented on src/main/java/core/basesyntax/Rectangle.java
> +            return this.width.equals(width) && this.length.equals(length);
colot is also required

2019-08-21 20:12 UTC, TarasHryts commented on src/main/java/core/basesyntax/Rectangle.java
> +            return this.width.equals(width) && this.length.equals(length);
corrected

2019-08-22 09:09 UTC, boroda4436 requested changes

2019-08-22 09:09 UTC, boroda4436 commented on src/main/java/core/basesyntax/Rectangle.java
> +import java.util.Objects;
@TarasHryts lets not use import java.util.Objects;

2019-12-03 07:55 UTC, closed without merging